feat(hiyobi_bookmark_downloader): add hiyobi_bookmark_downloader
KurtBestor/Hitomi-Downloader pull request #2856
Opened 2020-12-17 00:04 UTC by SaidBySolo

2020-12-17 03:28 UTC, KurtBestor requested changes
다음과 같이 `Downloader.print_` 쓰시면 돼요:
https://github.com/KurtBestor/Hitomi-Downloader/blob/4ba8a57ebb559de07d826fa5a3e5dd9e7b0b64e4/src/extractor/twitter_downloader.py#L103

2020-12-17 03:28 UTC, KurtBestor commented on src/extractor/hiyobi_bookmark_downloader.py
> +        self.url: str = self.url.replace("hiyobibookmark_", "").split("/")
Downloader.url 은 str 타입이여야 해요.

2020-12-17 03:53 UTC, SaidBySolo commented on src/extractor/hiyobi_bookmark_downloader.py
> +        self.url: str = self.url.replace("hiyobibookmark_", "").split("/")
앗 빠르게 코딩하느라 미쳐못봤네요 수정했어요!

2020-12-17 04:57 UTC, KurtBestor commented on src/extractor/hiyobi_bookmark_downloader.py
>          if not len(self.url) == 2:
이것도 고쳐주세요

2020-12-17 04:58 UTC, KurtBestor requested changes

2020-12-17 04:58 UTC, KurtBestor commented on src/extractor/hiyobi_bookmark_downloader.py
>          if not len(self.url) == 2:
이것도 고쳐주세요

2020-12-17 05:24 UTC, SaidBySolo commented on src/extractor/hiyobi_bookmark_downloader.py
>          if not len(self.url) == 2:
수정했습니당

2020-12-17 06:36 UTC, KurtBestor commented
hastebin 에 업로드 하는 이유가 있나요?

2020-12-17 07:03 UTC, SaidBySolo commented
> hastebin 에 업로드 하는 이유가 있나요?

https://github.com/KurtBestor/Hitomi-Downloader/pull/2856/files#diff-76e2830f275813c6b42c84e900772bf58049c32d56281725014348749993ab41R42

여기에 최종적으로 태그가 모여지게 되는데,

시도는 안해봤긴 하지만 with open으로 파일을 써볼까했는데 ``self.urls.append`` 를 해줘야 할거 같아서

api키도 필요없고 30일 이후에 삭제되니까 그나마 괜찮은 hastebin에 업로드 후에 다운받게 해놨어요.

그외에 다른이유는 없어요.

2020-12-17 07:27 UTC, KurtBestor commented
다음과 같이 URL 대신 BytesIO 를 넣으면 해당 바이트를 파일에 써요: https://github.com/KurtBestor/Hitomi-Downloader/blob/dd256995fa3ef2fd202ceaebd5592512c586ebba/src/extractor/hameln_downloader.py#L63-L74

BytesIO 구현으로 바꿔주시는 게 좋을 것 같아요.

2020-12-17 08:10 UTC, SaidBySolo commented
> 다음과 같이 URL 대신 BytesIO 를 넣으면 해당 바이트를 파일에 써요:
> 
> https://github.com/KurtBestor/Hitomi-Downloader/blob/dd256995fa3ef2fd202ceaebd5592512c586ebba/src/extractor/hameln_downloader.py#L63-L74
> 
> BytesIO 구현으로 바꿔주시는 게 좋을 것 같아요.

구현완료 했습니다.

추가적으로 사용자가 이거 왜 안돼는거 같지 할거 같아서
소스 참고해서 progress 비스무리 구현했어요.

2020-12-23 02:32 UTC, KurtBestor commented
좀 마이너한 기능이어서 [Scripts](https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts) 에 추가했어요.

2020-12-23 03:12 UTC, SaidBySolo commented
Was added [here](https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts)

There is no problem with closing the pull request.

2020-12-23 03:12 UTC, closed without merging

2020-12-23 03:25 UTC, SaidBySolo commented
https://github.com/KurtBestor/Hitomi-Downloader/pull/2856/files#diff-76e2830f275813c6b42c84e900772bf58049c32d56281725014348749993ab41R71

이줄 str이 아닐경우 리턴해야하는데 모르고 not을 안썻네요.

수정해주시면 감사하겠어요!